### ISSUE TITLE
Get Error 

### ISSUE THREAD

**Issue by Sajibekanti** [UndeadSec/EvilURL#2]
Get This type Of Error For Me 

Insert name: example
 Insert level domain: .com

Insert name: honeycomb
Insert level domain: .io
Traceback (most recent call last):
  File "C:\Users\root\Desktop\evil\evilurl.py", line 107, in <module>
    main()
  File "C:\Users\root\Desktop\evil\evilurl.py", line 58, in main
    makeEvil('c', names[1], unicodes[1], url.replace('c', u'╧▓'), end)
  File "C:\Users\root\Desktop\evil\evilurl.py", line 40, in makeEvil
    print '\n{2}[*] Char replaced: %s\n[*] Using Unicode: %s\n[*] Unicode number: %s\n{0}[*] Evil url: %s%s{1}\n-------------------------------'.format(GREEN, END, YELLOW) % (char, unicd, uninum, newurl, end)
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u03f2' in position 125: character maps to <undefined>

**Comment by A1S0N** [comment]
Try now with Python3 version

**Comment by A1S0N** [comment]
Please check:
https://github.com/UndeadSec/EvilURL/issues/3
